[package]
name = "maiq-web"
version = "0.1.1"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.8.0", features = ["web-rocket"] }
thiserror = "1.0.37"
# maiq_parser = { git = "https://github.com/pashokitsme/maiq-parser", version = "0.1.0" }
sqlx = { version = "0.6.2", features = ["postgres", "runtime-tokio-native-tls"] }
serde = { version = "1.0.151", features = ["serde_derive"] }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
dotenvy = "0.15.6"
maiq_parser = { git = "https://github.com/pashokitsme/maiq-parser", version = "0.1.5" }
